apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

images:
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.0

patches:
- target:
    kind: Service
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30083
